# Generated by Django 4.0.5 on 2022-06-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tasks_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
